### ISSUE TITLE
error opening the win 32 application

### ISSUE THREAD

**Issue by gavbn** [Xonshiz/Hulu-Subs-Downloader#7]
Hi,when I try to open the application I get an error saying that 
HuluSubsDownloader.exe entry point not found
the procedure entry point ucrtbase.terminate could not be located in the dynamic link library api-ms-win-crt-runtime-l1-1-0.dll.

I am using the 32 bit windows

**Comment by Xonshiz** [comment]
A quick google search tells me that it's related to OS.
Please first try these two links and then let me know if it fixed the problem or not : 

1.) [YouTube Tutorial](https://www.youtube.com/watch?v=5554vP3IZxo)

2.) [MicroSoft Thread](https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/the-procedure-entry-point-ucrtbaseterminate-could/e45c2162-bb43-4082-a3dd-d715c7ea1f46)

**Comment by gavbn** [comment]
thanks for the quick reply but I am still getting an error from the cmd and here is the error:
C:\Users\User\Downloads>hulus
Enter a URL : http://www.hulu.com/watch/1045926
Which format do you want : srt
Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 594, in
 urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 350, in
 _make_request
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 835, in
 _validate_conn
  File "site-packages\requests\packages\urllib3\connection.py", line 323, in con
nect
  File "site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_
wrap_socket
  File "ssl.py", line 377, in wrap_socket
  File "ssl.py", line 752, in __init__
  File "ssl.py", line 988, in do_handshake
  File "ssl.py", line 633, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c
:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 624, in
 urlopen
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "HuluSubsDownloader.py", line 87, in <module>
  File "HuluSubsDownloader.py", line 22, in __init__
  File "HuluSubsDownloader.py", line 27, in singleEpisode
  File "site-packages\requests\sessions.py", line 501, in get
  File "site-packages\cfscrape\__init__.py", line 34, in request
  File "site-packages\requests\sessions.py", line 488, in request
  File "site-packages\requests\sessions.py", line 630, in send
  File "site-packages\requests\sessions.py", line 630, in <listcomp>
  File "site-packages\requests\sessions.py", line 190, in resolve_redirects
  File "site-packages\requests\sessions.py", line 609, in send
  File "site-packages\requests\adapters.py", line 497, in send
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed (_ssl.c:645)
Failed to execute script HuluSubsDownloader

**Comment by Xonshiz** [comment]
Thanks for the detailed output. I'll look into this issue :)

**Comment by gavbn** [comment]
In the meantime,if you don't mind could tell me any other means of downloading subtitles from hulu

**Comment by Xonshiz** [comment]
umm try the python file?

**Comment by gavbn** [comment]
I am sorry for asking this question but how to run the python file on windows

**Comment by Xonshiz** [comment]
Leave it, I'll try to fix this by tomorrow ...

**Comment by gavbn** [comment]
ok,thanks for the support and I hope you fix this issue asap

**Comment by Xonshiz** [comment]
Pushed an update for this. Windows Binary is working now and the subs are downloading just fine, so I'm closing this. If you still have problem, let me know, I'll re-open.
